apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-example
spec:
  # Create a volume called 'shared-logs' that the
  # app and sidecar share.
  volumes:
  - name: shared-logs 
    emptyDir: {}

  # In the sidecar pattern, there is a main application
  # container and a sidecar container.
  containers:
   # Sidecar container
  - name: sidecar-container
    # simple sidecar: busybox creates logs in the same
    # location as main application with a timestamp
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo  $(date -u) 'This is just an echo from simple Sidecar Container' >> /var/log/index.html; sleep 5;done"]
    resources: {}

    # Mount the pod's shared log file into the sidecar
    # container. In this case, nginx will serve the files
    # in this directory.
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
    # Main application container
  - name: main-container
    # Simple application: nginx serving on the port 80 that takes the index.html
    # from the volume mount workdir location
    image: nginx
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
